# The sequence of triangle numbers is generated by adding the natural numbers. 
# So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
#   
#   1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
# 
# Let us list the factors of the first seven triangle numbers:
#   
#   1: 1
#   3: 1,3
#   6: 1,2,3,6
#   10: 1,2,5,10
#   15: 1,3,5,15
#   21: 1,3,7,21
#   28: 1,2,4,7,14,28
#
# We can see that 28 is the first triangle number to have over five divisors.
# 
# What is the value of the first triangle number to have over five hundred divisors?



install.packages("gmp")

library(gmp)

t_num = 0
n = 1
divs = 1

while(T) {
  t_num = t_num + n
  n = n + 1
  prims = factorize(t_num)
  if(length(prims) > 1) {
    my_divs = 1
    uni_prims = unique(prims)
    for(i in seq_along(uni_prims)) {
      my_divs = my_divs * (sum(uni_prims[i] == prims) + 1)
    }
    if(my_divs > divs) {
      divs = my_divs
    }
    if(divs > 500)
      break
  }
}

t_num


